# Generated by Django 3.2.21 on 2023-09-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='blog.gamecategory'),
        ),
    ]
