# Generated by Django 3.2.21 on 2023-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='device',
        ),
        migrations.AddField(
            model_name='post',
            name='device',
            field=models.CharField(choices=[('PC', 'PC'), ('Nintendo', 'Nintendo'), ('Xbox', 'Xbox'), ('PlayStation', 'PlayStation')], default=None, max_length=20),
        ),
    ]
