# Generated by Django 3.2.21 on 2023-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230930_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Citizen of the Cyber world', max_length=26),
        ),
    ]
